export const RequestMethod = [
  {label: 'GET', value: 'GET'},
  {label: 'POST', value: 'POST'},
  {label: 'PUT', value: 'PUT'},
  {label: 'DELETE', value: 'DELETE'},
]

export const RequestHeader = [
  {label: 'Accept', value: 'Accept'},
  {label: 'Accept-Charset', value: 'Accept-Charset'},
  {label: 'Accept-Encoding', value: 'Accept-Encoding'},
  {label: 'Accept-Datetime', value: 'Accept-Datetime'},
  {label: 'Accept-Language', value: 'Accept-Language'},
  {label: 'Authorization', value: 'Authorization'},
  {label: 'Cache-Control', value: 'Cache-Control'},
  {label: 'Connection', value: 'Connection'},
  {label: 'Content-Length', value: 'Content-Length'},
  {label: 'Content-MD5', value: 'Content-MD5'},
  {label: 'Content-Type', value: 'Content-Type'},
  {label: 'Cookie', value: 'Cookie'},
  {label: 'Date', value: 'Date'},
  {label: 'Expect', value: 'Expect'},
  {label: 'Forwarded', value: 'Forwarded'},
  {label: 'From', value: 'From'},
  {label: 'Host', value: 'Host'},
  {label: 'If-Match', value: 'If-Match'},
  {label: 'If-Modified-Since', value: 'If-Modified-Since'},
  {label: 'If-None-Match', value: 'If-None-Match'},
  {label: 'If-Range', value: 'If-Range'},
  {label: 'If-Unmodified-Since', value: 'If-Unmodified-Since'},
  {label: 'Max-Forwards', value: 'Max-Forwards'},
  {label: 'Origin', value: 'Origin'},
  {label: 'Pragma', value: 'Pragma'},
  {label: 'Proxy-Authorization', value: 'Proxy-Authorization'},
  {label: 'Range', value: 'Range'},
  {label: 'Referer', value: 'Referer'},
  {label: 'TE', value: 'TE'},
  {label: 'Upgrade', value: 'Upgrade'},
  {label: 'User-Agent', value: 'User-Agent'},
  {label: 'Via', value: 'Via'},
  {label: 'Warning', value: 'Warning'},
]
